name = "Nacdlow Marketplace"
license = ""
licenselink = ""
description = ""
homepage = "https://gitlab.com/group-nacdlow"
tags = []
features = []
min_version = "0.40"

[author]
  name = "Nacdlow"
  homepage = "https://nacdlow.com"
